name: Sync-Fork-and-CI-CD-to-ECS

on:
  #push:
  #  branches:
  #   - main
  #schedule:
  #    actually, ~5 minutes is the highest
  #    effective frequency you will get
  # - cron:  '*/5 * * * *'
  workflow_dispatch:
  
env:
  AWS_REGION: us-east-2                     # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: vc                        # set this to your Amazon ECR repository name
  ECS_SERVICE: VC-issuer-test               # set this to your Amazon ECS service name
  ECS_CLUSTER: ECS-cluster-nodes            # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: VC-issuer-test       # set this to the path to your Amazon ECS task definition
                                            # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: VC-issuer-container       # set this to the name of the container in the
                                            # containerDefinitions section of your task definition
  
jobs:
    create_image:
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
     - uses: 
  
