name: Sync Fork

on:
  #schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
   #- cron:  '*/5 * * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'krylovlf'
          git config --global user.email 'krylovlf@gmail.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/Azure-Samples/active-directory-verifiable-credentials.git
          git fetch upstream

          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          git checkout -b krylovlf/active-directory-verifiable-credentials/main Azure-Samples/active-directory-verifiable-credentials/main
          git merge --no-edit krylovlf/active-directory-verifiable-credentials/main
          git push origin Azure-Samples/active-directory-verifiable-credentials

          git checkout main
          git merge --no-edit active-directory-verifiable-credentials/main
          git push origin main

          # etc
