name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: Azure-Samples/active-directory-verifiable-credentials
        with:
          owner: krylovlf
          base: main
          head: main
